# Convert a distance matrix into a long dataframe where each row
# is a pair of identical sequences
get_df_pairs_identical_seq_from_dist_mat <- function(dist_mat){
  df_pairs <- df_pairs_identical_seq <- dist_mat %>% 
    as_tibble() %>% 
    mutate(label_tip_1 = rownames(dist_mat)) %>% 
    pivot_longer(cols = - 'label_tip_1', names_to = 'label_tip_2', values_to = 'n_mut') %>% 
    filter(label_tip_1 != label_tip_2, n_mut == 0)
  
  return(df_pairs)
}

# Convert a distance matrix into a long dataframe where each row
# is a pair of sequences separated by less than a n_mut_away Hamming distance
get_df_pairs_less_n_mut_away_from_dist_mat <- function(dist_mat, n_mut_away){
  df_pairs <- df_pairs_identical_seq <- dist_mat %>% 
    as_tibble() %>% 
    mutate(label_tip_1 = rownames(dist_mat)) %>% 
    pivot_longer(cols = - 'label_tip_1', names_to = 'label_tip_2', values_to = 'n_mut') %>% 
    filter(label_tip_1 != label_tip_2, n_mut <= n_mut_away)
  
  return(df_pairs)
}

# Compute RR of pairs of sequences being in two groups
# from a long dataframe (generated by get_df_pairs_identical_seq_from_dist_mat
# or get_df_pairs_less_n_mut_away_from_dist_mat) and a metadatafile
get_RR_from_df_pairs <- function(df_pairs, metadata){
  tmp_df <- df_pairs %>% 
    left_join(metadata, by = c('label_tip_1' = 'label')) %>% 
    rename(subgroup_1 = subgroup) %>% 
    left_join(metadata, by = c('label_tip_2' = 'label')) %>% 
    rename(subgroup_2 = subgroup) %>% 
    filter(! is.na(subgroup_1), ! is.na(subgroup_2)) %>% 
    group_by(subgroup_1, subgroup_2) %>% 
    summarise(n_pairs = n()) %>% 
    group_by(subgroup_1) %>% 
    mutate(n_pairs_1_x = sum(n_pairs)) %>% 
    group_by(subgroup_2) %>% 
    mutate(n_pairs_x_2 = sum(n_pairs)) %>% 
    ungroup() %>% 
    mutate(n_pairs_x_x = sum(n_pairs),
           log_RR = log(n_pairs) - log(n_pairs_1_x) - log(n_pairs_x_2) + log(n_pairs_x_x))
  
  return(tmp_df)
}

# Perform a subsampling approach to generate uncertainty around 
# RR (n_subsamples subsample replicate sampling prop_subsample of the entire dataset)
get_df_uncertainty_RR <- function(df_pairs, metadata_seq, prop_subsample, n_subsamples){
  
  n_sequences <- nrow(metadata_seq)
  
  df_subsample_RR <- Reduce('bind_rows', lapply(1:n_subsamples, FUN = function(i_subsample){
    id_to_keep <- sample(1:n_sequences, size = round(n_sequences * prop_subsample), replace = F)
    metadata_seq_subsample <- metadata_seq[id_to_keep, ]
    get_RR_from_df_pairs(df_pairs, metadata_seq_subsample) %>% 
      mutate(i_subsample = i_subsample)
  }))
  
  return(df_subsample_RR)
}